name: 📚 Documentation
description: Report issues with documentation or suggest improvements
title: "[DOCS] "
labels: ["documentation", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 📚 Documentation Issue
        
        Help us improve our documentation! This can include README files, code comments, setup guides, or any other project documentation.

  - type: dropdown
    id: doc-type
    attributes:
      label: 📄 Documentation Type
      description: What type of documentation does this relate to?
      options:
        - 📖 README.md
        - 🤝 CONTRIBUTING.md
        - 🔒 SECURITY.md
        - 📋 Feature documentation (CRAWLER_PROTECTION.md, etc.)
        - 💻 Code comments/inline documentation
        - 🚀 Setup/Installation guide
        - 🔧 Development workflow
        - 📊 API documentation
        - 🎨 Design guidelines
        - 📝 User guide
        - Other (specify below)
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: 🎯 Issue Type
      description: What kind of documentation issue is this?
      options:
        - 🐛 Error/Incorrect information
        - ❓ Missing information
        - 😕 Unclear/Confusing content
        - 📱 Missing mobile instructions
        - 🔄 Outdated information
        - ✨ Enhancement suggestion
        - 🌐 Accessibility improvement
        - 📊 Better organization needed
        - 🎨 Formatting/Style issue
        - 🔗 Broken links
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: 📍 Location
      description: Where is the documentation issue located?
      placeholder: |
        Specific location:
        - File: [filename.md]
        - Section: [section title]
        - Line number: [if applicable]
        - URL: [if web-based]
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: 📄 Current Content
      description: What does the current documentation say? (copy the problematic text)
      placeholder: |
        Current text/content:
        ```
        [paste the current problematic content here]
        ```
      render: markdown

  - type: textarea
    id: issue-description
    attributes:
      label: 🐛 Issue Description
      description: What's wrong with the current documentation?
      placeholder: |
        The problem is:
        - [Specific issue 1]
        - [Specific issue 2]
        
        This causes confusion because...
    validations:
      required: true

  - type: textarea
    id: suggested-improvement
    attributes:
      label: ✅ Suggested Improvement
      description: How should the documentation be improved?
      placeholder: |
        Suggested changes:
        ```
        [Your suggested improved content here]
        ```
        
        This would be better because...
      render: markdown
    validations:
      required: true

  - type: dropdown
    id: target-audience
    attributes:
      label: 👥 Target Audience
      description: Who is the primary audience for this documentation?
      options:
        - 👨‍💻 Developers (team members)
        - 🆕 New contributors
        - 🔧 DevOps/Infrastructure
        - 🎨 Designers
        - 📊 Project managers
        - 🏢 Business stakeholders
        - 👤 End users
        - 🔒 Security team
        - Everyone
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: ⏰ Urgency
      description: How urgent is this documentation fix?
      options:
        - 🚨 Critical - Blocks development/deployment
        - ⚠️ High - Causes significant confusion
        - 📢 Medium - Moderate improvement needed
        - 📝 Low - Minor enhancement
    validations:
      required: true

  - type: textarea
    id: user-impact
    attributes:
      label: 👤 User Impact
      description: How does this documentation issue affect users?
      placeholder: |
        Impact on users:
        - New developers can't [specific action]
        - Contributors are confused about [process]
        - Setup instructions don't work for [scenario]
        - Missing information about [feature]

  - type: textarea
    id: context
    attributes:
      label: 🔍 Additional Context
      description: Any other context that would help improve the documentation
      placeholder: |
        Additional context:
        - Related to [other documentation]
        - Discovered while [doing what]
        - Affects [specific workflow]
        - Similar issues in [other files]

  - type: checkboxes
    id: scope
    attributes:
      label: 📋 Documentation Scope
      description: What aspects should be considered when fixing this?
      options:
        - label: 📱 Mobile/responsive considerations
        - label: 🌐 Accessibility guidelines
        - label: 🔗 Cross-references to other documentation
        - label: 📸 Screenshots or diagrams needed
        - label: 💻 Code examples required
        - label: 🔄 Step-by-step instructions
        - label: ⚠️ Warning/caution notes
        - label: 🎯 Beginner-friendly explanations
        - label: 🔧 Advanced configuration options
        - label: 🧪 Testing instructions

  - type: textarea
    id: related-docs
    attributes:
      label: 🔗 Related Documentation
      description: Are there other documentation files that should be updated together?
      placeholder: |
        Related files that might need updates:
        - [filename1.md] - because...
        - [filename2.md] - to maintain consistency
        - Code comments in [file.ts] - to match

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have checked if similar documentation issues already exist
          required: true
        - label: I have provided specific location information
          required: true
        - label: I have suggested concrete improvements
          required: true
        - label: I have considered the target audience
          required: false
